### ISSUE TITLE
HW1 To-Do List

### ISSUE THREAD

**Issue by Jordan883** [Jordan883/MBSE-Jordan-Fernandes#1]
## Lab 1 (Homework Setup)
- [x] Install Git/GitHub
- [x] Create first repo (and follow steps for ReadMe setup)
## Homework 1
- [x] Complete Learning Git lessons
  - [x] Introduction
  - [x] Ramping Up
  - [x] Moving Work Around
  - [x] A Mixed Bag
  - [x] Advanced Topics
- [x] Screenshot lessons in submission
- [ ] Review Git Lessons/Take Notes
- [x] Create HW1 To-Do List Issue
- [x] Link repo in submission
- [x] Submit quiz
- [x] Create a team for the semester project
- [x] Email Prof. Yang with team makeup by Sunday
